/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReraRouteImport } from './routes/rera'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReraRoute = ReraRouteImport.update({
  id: '/rera',
  path: '/rera',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/grievance': typeof GrievanceRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/refund': typeof RefundRoute
  '/rera': typeof ReraRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/grievance': typeof GrievanceRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/refund': typeof RefundRoute
  '/rera': typeof ReraRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/grievance': typeof GrievanceRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/refund': typeof RefundRoute
  '/rera': typeof ReraRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/grievance'
    | '/privacy'
    | '/properties'
    | '/refund'
    | '/rera'
    | '/services'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/grievance'
    | '/privacy'
    | '/properties'
    | '/refund'
    | '/rera'
    | '/services'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/grievance'
    | '/privacy'
    | '/properties'
    | '/refund'
    | '/rera'
    | '/services'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GrievanceRoute: typeof GrievanceRoute
  PrivacyRoute: typeof PrivacyRoute
  PropertiesRoute: typeof PropertiesRoute
  RefundRoute: typeof RefundRoute
  ReraRoute: typeof ReraRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rera': {
      id: '/rera'
      path: '/rera'
      fullPath: '/rera'
      preLoaderRoute: typeof ReraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  GrievanceRoute: GrievanceRoute,
  PrivacyRoute: PrivacyRoute,
  PropertiesRoute: PropertiesRoute,
  RefundRoute: RefundRoute,
  ReraRoute: ReraRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
